### ISSUE TITLE
modify task

### ISSUE THREAD

**Issue by RobertMyles** [bnosac/cronR#1]
Is there a way to modify a task, like taskscheduleR's `modify` argument to `taskscheduler_create()`? 
I would like to run a task every 10 minutes, but the options for `cron_add()` are only "minutely", "hourly", "daily", "monthly", or "yearly".

**Comment by jwijffels** [comment]
Does this work for you.
```

library(cronR)
f <- system.file(package = "cronR", "extdata", "helloworld.R")
cron_add(cron_rscript(f), frequency = 'hourly', 
         at = c("00:05", "00:15", "00:25", "00:35", "00:45", "00:55"), 
         id = 'jobid', description = 'jobdescription')
```

**Comment by RobertMyles** [comment]
Sure! I just thought maybe there was a neater way. Thanks.

**Comment by jwijffels** [comment]
Do you mean something like this?

```
cron_add(cron_rscript(f), frequency = 'hourly', 
         at = c(5,15,25,35,45,55), 
         id = 'jobid', description = 'jobdescription')
```

**Comment by RobertMyles** [comment]
No, sorry! :-) What I meant was, something like `modify = "5"` is very useful, whereas `at = c(5, 15, 25, 35, 45, 55)` is much more typing!

**Comment by jwijffels** [comment]
are there other use cases you had in mind with this?

**Comment by RobertMyles** [comment]
No, I was just looking for a handy way to schedule a function to run every 15 minutes. Thanks for your time.
