### ISSUE TITLE
Application of cronR in Shiny App scheduled task

### ISSUE THREAD

**Issue by englianhu** [bnosac/cronR#10]
Hi,

I know about you via https://github.com/bnosac/cronR.

I am currently conducting research on real-time trading. I have 2 questions about real-time trading on shiny app.

1) Start calculate the forecast price everyday 00:00AM.
2) Matching a real-time bid/ask price to close a transaction.

source questions : https://community.rstudio.com/t/application-of-cronr-in-shiny-app-scheduled-task/9292/5

I do appreciate if you are willing shade me a light.
Thank you.

Best Regards
Ryo, Eng Lian Hu

**Comment by jwijffels** [comment]
Which type of light you want me to shade? Your application runs every day using a cron job and next you apparently run a shiny app which does some calculation every 750 milliseconds. What is exactly the question?

**Comment by jwijffels** [comment]
Closing as this is not really a question. Feel free to reopen if you have questions which are specific.
