### ISSUE TITLE
Problem programming a function monthly

### ISSUE THREAD

**Issue by MariaMetriplica** [bnosac/cronR#11]
Hi, I've trying to programm a function montly. I want that my function to run the first day every month at 2:00. Then, I've used this command:

```
library(cronR,)
    cmd<- cron_rscript("Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.R")
    cron_add(cmd, frequency = 'monthly', 
             id = 'informe_mensual,
             days_of_month = "first",
             at = '02:00',
             description = 'Informe_mensual_Visits_Orders')
```

But, when I used cron_ls(), R returs this:

```
## cronR job
## id:   informe_mensual
## tags: 
## desc: Informe_mensual_Visits_Orders
0 2 1 * 1 /usr/lib/R/bin/Rscript 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.R'  >> 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.log' 2>&1
```

Then, my function runs every monday. Does CronR define days_of_week =1 automatically?Is there any solution to solve this problem?
Thank you!

**Comment by MariaMetriplica** [comment]
Sorry, I've publish my message before to finish the redaction accidentally. When I used cron_ls(), R returs this:

```
## cronR job
## id:   informe_mensual_Camper
## tags: 
## desc: Informe_mensual_Camper_Visits_Orders
0 2 1 * 1 /usr/lib/R/bin/Rscript 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.R'  >> 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.log' 2>&1
```
I don't know why cronR associate 1 to days_of_week.

**Comment by jwijffels** [comment]
You need to give the full path to your R script. E.g. file.path(getwd(), "Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.R") when typing cron_rscript 
And understand wat 0 2 1 * 1 means by looking at https://en.wikipedia.org/wiki/Cron
next use day_of_month="*"

**Comment by MariaMetriplica** [comment]
When I use `days_of_week="*"` it takes all days of week. I see this when I use cron_ls():

```
> cron_ls()
## cronR job
## id:   informe_mensual_Camper
## tags: 
## desc: Informe_mensual_Camper_Visits_Orders
0 2 1 * 0,1,2,3,4,5,6 /usr/lib/R/bin/Rscript 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.R'  >> 'Informe_Mensual_Visits_Orders/Automatizar_Informes_Mensuales.log' 2>&1
```
Besides, I've tried to provide the cron string directly and I receive an error:
```
cron_add(cmd, frequency = '0 2 1 * *', 
          id = 'informe_mensual_Camper',
          description = 'Informe_mensual__Visits_Orders')
```
```
Error in cron_add(cmd, frequency = "0 2 1 * *", id = "informe_mensual_Camper",  : 
  Unrecognized string passed to frequency: '0 2 1 * *'
```

**Comment by jwijffels** [comment]
That's the point that days_of_week="*" takes all days of week
For the frequency = "0 2 1 * *" you need to have version 0.4 of the package installed (check your version with installed.packages()["cronR", ])

**Comment by MariaMetriplica** [comment]
Thank you! It works :)
