### ISSUE TITLE
Cant delete jobs. All sub-lists in "choices" must be named.

### ISSUE THREAD

**Issue by bernardolares** [bnosac/cronR#12]
Hello guys.
I've been using this super cool library for a while now and works like a charm. 
But, today I had the following problem: when I opened the plugin window, and go to `Manage existing jobs`, I get the `All sub-lists in "choices" must be named.` error (see attachment for screenshot)

<img width="749" alt="captura de pantalla 2018-06-06 a la s 12 15 20 p m" src="https://user-images.githubusercontent.com/37635772/41054300-9697e178-6983-11e8-9c74-2ff781e75309.png">

I tried manually removing the last created job with the `cron_rm("id")` function but it returns the `Error in !to_keep : invalid argument type` error.
Any suggestions?

R version `3.4.3`
cronR version `0.4.0`

**Comment by jwijffels** [comment]
I have no id, but my guess would be that you have several jobs with the same id which is not allowed.
Can you inspect that with cron_ls() or share your cron schedule?

**Comment by bernardolares** [comment]
Sorry for the big code, but this is what I have... at the end you can see there are two `super_hubspot_01` but I can't delete either!
`> cron_ls()
## cronR job
## id:   daily_report_hourly
## tags: daily_report_hourly
## desc: daily_report_hourly
33 * * * * /usr/lib/R/bin/Rscript '/home/bernardo/DailyReport/daily_report.R'  >> '/home/bernardo/DailyReport/daily_report.log' 2>&1

## cronR job
## id:   adi_mails_hourly
## tags: adi_mails_hourly
## desc: adi_mails_hourly
8 * * * * /usr/lib/R/bin/Rscript '/home/bernardo/ADIs/ADI_dropbox.R'  >> '/home/bernardo/ADIs/ADI_dropbox.log' 2>&1

## cronR job
## id:   mails_stocks_7pm
## tags: 
## desc: I execute things
1 0 * * * /usr/lib/R/bin/Rscript '/home/bernardo/Mails/stocks.R'  >> '/home/bernardo/Mails/stocks.log' 2>&1

## cronR job
## id:   renovaciones
## tags: 
## desc: I execute things
5 17 * * * /usr/lib/R/bin/Rscript '/home/bernardo/Renovaciones/gsheet.R'  >> '/home/bernardo/Renovaciones/gsheet.log' 2>&1

## cronR job
## id:   test1
## tags: 
## desc: Leads Categories
0 0 * * * 

## cronR job
## id:   logins_mail
## tags: Logins diarios
## desc: Logins diarios
15 16 * * * /usr/lib/R/bin/Rscript '/home/bernardo/Logins/logins.csv'  >> '/home/bernardo/Logins/logins.log' 2>&1

## cronR job
## id:   daily_auc
## tags: 
## desc: daily_auc
0 21 * * * /usr/lib/R/bin/Rscript '/home/bernardo/DailyAUC/DailyAUC.R'  >> '/home/bernardo/DailyAUC/DailyAUC.log' 2>&1

## cronR job
## id:   llamadas
## tags: 
## desc: llamadas
0 * * * * /usr/lib/R/bin/Rscript '/home/bernardo/Llamadas/primeras_llamadas.R'  >> '/home/bernardo/Llamadas/primeras_llamadas.log' 2>&1

## cronR job
## id:   every5min
## tags: leads_assignment_job
## desc: I execute things
*/5 * * * * /usr/lib/R/bin/Rscript '/home/bernardo/LeadsAssignment/leads_assignment.R'  >> '/home/bernardo/LeadsAssignment/leads_assignment.log' 2>&1

## cronR job
## id:   super_hubspot
## tags: 
## desc: super_hubspot
*/30 * * * * /usr/lib/R/bin/Rscript '/home/bernardo/SuperHubspot/super_deals.R'  >> '/home/bernardo/SuperHubspot/super_deals.log' 2>&1

## cronR job
## id:   super_hubspot_01
## id:   super_hubspot_01
## tags: 
## desc: Super Hubspot tables, every 15 min */15 * * * * 1528286822.09469
##   cronR job id: super_hubspot_01 tags: Super Hubspot tables, every 15
##   min
*/15 * * * * FALSE

## cronR job
## id:   super_hubspot_01
## tags: 
## desc: Super Hubspot tables, every 15 min
*/15 * * * * FALSE`

**Comment by jwijffels** [comment]
That's what I thought, 2 jobs with the same id. 
Does `cron_rm('super_hubspot_01')` fix this?

**Comment by bernardolares** [comment]
No, that's what I mentioned in the first post.. I get the `Error in !to_keep : invalid argument type` error

**Comment by jwijffels** [comment]
Well, if that is what it returns, you'll need to fix it into the crontab directly. Go to the shell and type crontab -e and fix it there.

**Comment by bernardolares** [comment]
Sorry but tried that as well and didn't work out for me. I clicked on the `Show job` and in the `Delete job `and get the same output.. the window closes and shows me the following message:

```
Listening on http://127.0.0.1:4891
Warning in desc_start:(length(cronR_job) - 1) :
  numerical expression has 2 elements: only the first used
Warning: Error in <Anonymous>: All sub-lists in "choices" must be named.
Stack trace (innermost first):
    85: <Anonymous>
    84: mapply
    83: choicesWithNames
    82: shiny::selectInput
    81: shiny::renderUI
    80: func
    79: origRenderFunc
    78: output$getFiles
     3: shiny::runApp
     2: shiny::runGadget
     1: cronR:::cron_rstudioaddin
Warning in desc_start:(length(cronR_job) - 1) :
  numerical expression has 2 elements: only the first used
Warning: Error in !: invalid argument type
Stack trace (innermost first):
    68: cron_rm
    67: observeEventHandler
     3: shiny::runApp
     2: shiny::runGadget
     1: cronR:::cron_rstudioaddin
```

**Comment by bernardolares** [comment]
Excellent, that did the work done! I entered the machine and edited the file deleting the rows not wanted. Thanks @jwijffels
