### ISSUE TITLE
Using cronR on Google Compute Engine

### ISSUE THREAD

**Issue by laziob** [bnosac/cronR#13]
Im trying to set up a cron on a VM with Rstudio, but I get the following error using the addin:

Adding cronjob:
---------------

 cronR job
 id:   job_c87a93d2999d0e7323dc0936556f9bae
 tags: 
 desc: I execute things
0-59 * * * * /usr/local/lib/R/bin/Rscript '/home/acceso/Capacitarte/AnalyticsDataUpload.R'  >> '/home/acceso/Capacitarte/AnalyticsDataUpload.R' 2>&1
Warning: Error in system: error in running command
  78: system
  75: cron_add
  74: observeEventHandler
   3: shiny::runApp
   2: shiny::runGadget
   1: cronR:::cron_rstudioaddin

I also tried creating a cron_rscript and the using cron_add but same error. Any idea on how to fix it?

Thanks!

**Comment by jwijffels** [comment]
Is your cron service running?

**Comment by laziob** [comment]
Im not sure what do you mean by cron service. The Error is thrown when adding a cron job, either by Addin or by console. The virtual machine is in fact running at http://35.199.81.228/ with no issues there, and installing the package and its dependencies is working fine too.

A similar error is thrown if I try to load a cron tab too

**Comment by jwijffels** [comment]
That's all fine, but is the cron service running as shown in the section Install in the README at https://github.com/bnosac/cronR

**Comment by laziob** [comment]
That was the issue! Thanks a lot for your help, is now working fine!
