### ISSUE TITLE
cron job only runs once mode

### ISSUE THREAD

**Issue by joaocunha1991** [bnosac/cronR#14]
Hi, 

Thanks for this nice package nice package. I've also setup a VM using Mark's googleComputeEngineR package and then installed cronR.

When I try to schedule cron jobs through the add-on it only runs scripts that I set to run on 'ONCE' mode. Any idea of a direction I could take to find out the cause?

As an example i've set up a hello_world.R script to print a couple of sentences. the hello_world.log file is not populated so I assume it doesn't run at all.

This is the test cronjob I've set:
**0-59 * * * * /usr/local/lib/R/bin/Rscript '/home/quba.tech/hello_world.R'  >> '/home/quba.tech/hello_world.log' 2>&1**

**Comment by joaocunha1991** [comment]
not sure but don't think so. trying to confirm but it's hard since i need root access on the vm to install procps on the docker to check processes (ps command not found). 

but i assume it runs since it's able to run the job correctly when i schedule to run ONCE in the cronR add-on

**Comment by jwijffels** [comment]
ONCE is not a schedule, it just runs Rscript once, it is not scheduled. Check if the cron daemon is running (e.g. `cron status`)

**Comment by joaocunha1991** [comment]
sudo cron status returns:

cron: can't lock /var/run/crond.pid, otherpid may be 4424: Resource temporarily unavailable

**Comment by jwijffels** [comment]
Does this work if you run it from the command line? 
`/usr/local/lib/R/bin/Rscript '/home/quba.tech/hello_world.R' >> '/home/quba.tech/hello_world.log'`

**Comment by joaocunha1991** [comment]
yes it does

**Comment by jwijffels** [comment]
well remove /home/quba.tech/hello_world.log and see after one minute if that log file is updated
