### ISSUE TITLE
ASIS Formatting

### ISSUE THREAD

**Issue by shuff703** [bnosac/cronR#15]
I'm trying to run cron jobs every 2 hours using the format `0 */2 * * *` when I run, it is exceeding my API rate limit.  I don't see any formatting guidelines in the readme so I'm wondering if this is a mistake I made or an issue with cronR.  I'd use every hour but I'll need to run several jobs on a 20 minute interval to avoid exceeding a rate limit.

**Comment by jwijffels** [comment]
This has nothing to do with cronR, ask your API provider of whatever you are doing to increase the limit or pay your API provider.

**Comment by jwijffels** [comment]
Documentation of a cron schedule is available at https://en.wikipedia.org/wiki/Cron
