### ISSUE TITLE
Cronjob cant be deleted

### ISSUE THREAD

**Issue by Timag** [bnosac/cronR#16]
First of all, thank you for the package!

I run in the following error, when attempting to delete a cronjob by id.

```
> cron_rm(id = "test2")
Removed 1 cron job.
new crontab file is missing newline before EOF, can't install.
```

In case the infos help:
- i dont have multiple jobs with same id
- i can add jobs without running in this error 
- jobs are also successfully executed

Before using cronR package i edited the crontab file "manually".
If i use the same command to manually check the file for missing newline i get a rather odd output:

```
rstudio@ip-199-99-99-6:~/dev $ sudo crontab -e
[sudo] password for rstudio:
73
```

So i dont see the jobs, but just "73". Is cronR saving the jobs in another file? What could i check to fix the error?

**Comment by jwijffels** [comment]
Looks like you need to add a newline just before the end of the file as the error message says as you edited the cron file manually in a wrong way.
You can access the cron file with
```
crontab -u yourusername -l
crontab -u yourusername -e
```
