### ISSUE TITLE
flock support

### ISSUE THREAD

**Issue by stanstrup** [bnosac/cronR#18]
Would there be a way to make sure that the previous process is finished before a new is launched?
I have seen that this should be done with flock.
So something like:
```r
* * * * * flock -n tmp/my.lockfile  sh -c 'command'  >> logpath 2>&1
```

**Comment by jwijffels** [comment]
I generally use either a bash file (e.g. called /home/bnosac/projectxyz/prox/test.sh) containing something like this

```
#!/bin/bash
/usr/lib/R/bin/Rscript '/home/bnosac/projectxyz/proc/test1.R'
/usr/lib/R/bin/Rscript '/home/bnosac/projectxyz/proc/test2.R'
```

And next schedule this with
`code <- cron_rscript("/home/bnosac/projectxyz/proc/test.sh", cmd = "/bin/bash")`
`cron_add(code, ...)`

**Comment by stanstrup** [comment]
Thanks for the hint. I finally got back to this.
I got it working with the following:


scheduled_tasks.sh file that contains

```bash
#!/bin/bash

[ "${FLOCKER}" != "$0" ] && exec env FLOCKER="$0" flock -n "$0" "$0" "$@" || :

/task_path/scheduled_tasks.R'
```


Run this to add job
```r
library(cronR)
cmd <- cron_rscript('/task_path/scheduled_tasks.sh', cmd = '/bin/bash', rscript_log = '/var/log/QC_cron.log')
cron_add(cmd, frequency = '*/1 * * * *', id = 'QC_processing', description = 'Process files every 1 minute')
```

**Comment by jwijffels** [comment]
Interesting use case, wasn't aware of this. Does flock also work on any Unix computer (e.g. also Mac?)

**Comment by stanstrup** [comment]
Not out of the box apparently: https://stackoverflow.com/questions/10526651/mac-os-x-equivalent-of-linux-flock1-command

What I am doing is running an R process in a docker container. The process should repeat about some time. But the process can take variable amount of time and should never be run in parallel. So this seem to make since that cannot happen.

I couldn't figure out how to add the cronjob correctly by hand but your package seem to do the job.

**Comment by jwijffels** [comment]
hmm, if it is not on Mac, I don't think I'll add that functionality in the package as it would make it linux only instead of unix-only
