### ISSUE TITLE
Shiny app creating a cron job

### ISSUE THREAD

**Issue by tatapoum** [bnosac/cronR#22]
I am trying to develop a shiny app that can create a cron job after doing some action.

I was wondering if the `shiny` user is able to do this operation (it works well with root).

I logged into my server with shiny user, opened an R session and typed the usual commands.
A cron job seems to be running, as I see it with `cron_ls()` but the data set that should be written every minut is not updated.

**Comment by jwijffels** [comment]
sure, that's possible

**Comment by tatapoum** [comment]
I retried it was simply a path and permissions issue... (working directory during a shiny session is in /srv/)

Thanks, I close this !
