### ISSUE TITLE
Job does not work + addin window is inactive also

### ISSUE THREAD

**Issue by axel-analyst** [bnosac/cronR#23]
Hi Kevin,

I faced some problems with running cronR job. I installed cron and cronR on Google Compute Engine. I cannot run the job and I see no one as well as log file.  Also, the window of cronR addin is inactive and I cannot take any action with it. Here is the code:
`cron_add(paste0("Rscript ", normalizePath("gsc2bq.R")), frequency = "hourly", at="15:56")
`

**My session info:**

```

`R version 3.6.2 (2019-12-12) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Debian GNU/Linux 10 (buster)  Matrix products: default BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.3.5.so  locale:  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8      [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                   [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C         attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] shiny_1.4.0 cronR_0.4.0  loaded via a namespace (and not attached):  [1] Rcpp_1.0.3       crayon_1.3.4     digest_0.6.24    later_1.0.0      mime_0.8         R6_2.4.1         jsonlite_1.6      [8] xtable_1.8-4     magrittr_1.5     pillar_1.4.3     rlang_0.4.4      rstudioapi_0.10  fs_1.3.1         miniUI_0.1.1.1   [15] promises_1.1.0   shinyFiles_0.7.5 tools_3.6.2      httpuv_1.5.2     fastmap_1.0.1    compiler_3.6.2   pkgconfig_2.0.3  [22] htmltools_0.4.0  tibble_2.1.3`

```

**Comment by jwijffels** [comment]
Two things:
- Is the cron daemon running as indicated in the README?
- Make sure that you installed the cronR package in a folder where you have write access rights to. If you don't have access to the location where you installed cronR (look at the path defined by installed.packages()["cronR", ]), install the cronR package as your own user in your own folder instead of a maybe system-wide folder where you don't have write access to.

**Comment by axel-analyst** [comment]
The problem was with Dockerfile and building the image
