### ISSUE TITLE
Issue with run script by Cron on GCP Debian

### ISSUE THREAD

**Issue by virton** [bnosac/cronR#24]
I have few scripts which I try to run by CronR from Google Compute Engine and RStudio Server. 
From Rstudio all scripts are works well. But then I try to run Cron it cause error 

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
Calls: dbWriteTable ... request_fetch -> request_fetch.write_memory -> <Anonymous>
Execution halted

Could you please help to fix it

**Comment by jwijffels** [comment]
This error is not related to the cronr package

**Comment by virton** [comment]
Actually this issue appear only then run CronR with Once settings. So, if it creates cron with schedule it works well
