### ISSUE TITLE
Librarys are not loaded from cron

### ISSUE THREAD

**Issue by DavidGarciaEstaun** [bnosac/cronR#25]
Hi,

I am trying to execute a cron, but when it's executed I get this error:
```
Error in library(odbc) : there is no package called ‘odbc’
Execution halted
```

This library is working because if I execute manually the same script it works well.
I think that maybe is an error with and update of R version or something like that.

Can you help me please?

Thanks in advance.
David.

**Comment by jwijffels** [comment]
This us not related to cronR. Look at .libPaths() to see what you have in your package directories which are used when a script runs.
