### ISSUE TITLE
When scheduling to send out SMS CronR messes up the message encoding.

### ISSUE THREAD

**Issue by YannisChourdakis** [bnosac/cronR#29]
Hi! I've been passionately using CronR to schedule my scripts but recently I tried to use it to automatically send SMS and the encoding of my message gets messed up only when I schedule my script with cronR when I manually run the script the message reaches the recipient in the correct encoding. Is there any solution here that I'm missing?

**Comment by jwijffels** [comment]
Inspect the LANG environment variable Sys.getenv('LANG') in the scheduled run and see where it differs from your local session.

**Comment by YannisChourdakis** [comment]
thanks @jwijffels it was true that the language of the SMS and the Sys.getenv('LANG') differed therefore changed it using: 

Sys.setlocale("LC_ALL","el_GR")
Sys.setenv(LANG="el_GR")
