### ISSUE TITLE
Can't see folder structure in the Addin within RStudio.

### ISSUE THREAD

**Issue by tarunparmar** [bnosac/cronR#3]
Firstly, thanks to a nice package. I was looking for a cron job utility on Google Cloud as the regular cron wasn't working as expect. I setup a VM using Mark's `googleComputeEngineR` package and then installed `cronR`. 

The Addin seems to work but I can't see folder, for some reason the system may be blocking due to permissions or something? Have you seen this before ?

![image](https://user-images.githubusercontent.com/17690950/34809427-e996c96e-f662-11e7-9b7d-e666480f7b99.png)

I tried to change folder permissions to 777 and also tried to set different working directory, but no luck.

**Comment by jwijffels** [comment]
The rstudio addin basically looks for settings in the location where cronR was installed and provides the following default folders when launching the cronR rstudio addin.
Can you provide the location where you installed cronR and these default folders.

```
installed.packages()["cronR", ]
c('Current working dir' = getwd(), 'HOME' = Sys.getenv('HOME'), 'R Installation' = R.home(), 'Root' = "/")

```
If these folders are all root-only folders and your user does not has the right to see these folders, maybe you just need to install the cronR package again as your user. Just do

`install.packages("cronR")`

Then when you load the R package, it's for sure it is accessing the folder you have rights to.

Please also provide information on `.libPaths()`

**Comment by tarunparmar** [comment]
Hi @jwijffels , thanks for quick response. 

When I installed cronR with `install.packages('cronR')` it got installed in `/usr/local/lib/R/site-library`
Here's the output of commands you wanted me to run 

```
> installed.packages()["cronR", ]
                                                           Package 
                                                           "cronR" 
                                                           LibPath 
                                   "/usr/local/lib/R/site-library" 
                                                           Version 
                                                           "0.3.0" 
                                                          Priority 
                                                                NA 
                                                           Depends 
                                                                NA 
                                                           Imports 
                                                          "digest" 
                                                         LinkingTo 
                                                                NA 
                                                          Suggests 
"knitr, miniUI, shiny (>= 0.11), shinyFiles (>= 0.6.0),\ntestthat" 
                                                          Enhances 
                                                                NA 
                                                           License 
                                              "MIT + file LICENSE" 
                                                   License_is_FOSS 
                                                                NA 
                                             License_restricts_use 
                                                                NA 
                                                           OS_type 
                                                            "unix" 
                                                            MD5sum 
                                                                NA 
                                                  NeedsCompilation 
                                                              "no" 
                                                             Built 
                                                           "3.4.3"
```
==========
``` 
> c('Current working dir' = getwd(), 'HOME' = Sys.getenv('HOME'), 'R Installation' = R.home(), 'Root' = "/")
Current working dir                HOME      R Installation                Root 
"/home/tarunparmar" "/home/tarunparmar"  "/usr/local/lib/R"                 "/" 
```
===========
```
> .libPaths()
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"   
```
This for sure is root folder. I may be able to set new path in my `/home/` directory where I have RW permissions. But I noticed something while I was doing this. I could not copy all the packages from site-library to the new location.

I went to command line but commandline tool could not find site-library folder in path probably because rstudio-server is running via docker image, not sure of that. 

I noticed the `rstudio` template runs as gcer user, is there any way I could run it as my user name `tarunparmar`?

**Comment by MarkEdmondson1234** [comment]
Just chipping in here, but checking you are doing everything from within the Docker container - easiest is to use RStudio terminal. Don’t install anything outside of Docker. Also is this using the Docker has cronR preinstalled or did you install it yourself?

**Comment by jwijffels** [comment]
@tarunparmar It seems to me that you might be better off installing the cronR package as your user tarunparmar as then it will be installed under /home/tarunparmar/R/... where you have the rights to.
Just install this from RStudio, not from the Docker container.
@MarkEdmondson1234 Where can I find the Docker code of this image he is using?

**Comment by MarkEdmondson1234** [comment]
@jwijffels I guess it is this one if @tarunparmar is using the standard RStudio (do correct me if wrong) https://github.com/cloudyr/googleComputeEngineR/blob/master/inst/dockerfiles/persistentRStudio/Dockerfile - perhaps he is working from this [blog post](http://code.markedmondson.me/4-ways-schedule-r-scripts-on-google-cloud-platform/)?

I have tried ones with `cronR` preinstalled but `RUN sudo service cron start` never seems to work, always have to log in and start it manually first time.  Any idea why that may be?

**Comment by jwijffels** [comment]
@MarkEdmondson1234 The question on RUN sudo service cron start seems off-topic for the question of @tarunparmar but if you are building your own docker files and want to make sure cron is started when the docker image is launched I think you can do something like this:

Create a file called docker-entrypoint.sh which looks something like this

```
#!/bin/bash

## Start up cron
service cron start

## Execute the supplied code
exec "$@"
```

And next in Dockerfile you put
`ENTRYPOINT ["docker-entrypoint.sh"]`

**Comment by tarunparmar** [comment]
I tried to copy the package directory to my user directory but that opened new can of worms. 
This is what I ran : 
```
my_rstudio <- gce_vm("rstudio-server", 
              template = "rstudio",
              predefined_type = "f1-micro",
              username = "tparmar", 
              password = "tparmar")
```
How do I install it as my user ? or be able to have a .libPath where I can install other packages ?

Is there any way I could use my custom template here instead of `template = "rstudio"`?

**Comment by MarkEdmondson1234** [comment]
@tarunparmar if you are using that template, when you log into RStudio, you are using your username and that is a user in Ubuntu, which is within the Docker container running RStudio. You should then be able to use the terminal from within RStudio to install cron and R to install cronR.

A custom template for this isn't available (yet).

**Comment by tarunparmar** [comment]
I am able to install packages and also install cronR by using `system("sudo apt-get install cron -y")`, for some reason the Terminal tab was not taking any keyboard input (¯\_(ツ)_/¯).

I think I may have to try running rstudio using custom container.

**Comment by tarunparmar** [comment]
Hi @jwijffels and @MarkEdmondson1234 , I tried running sample VMs (e.g. `hadleyverse-crontab`) but found same issue as I reported in the first comment. I can't change the folder in Shiny pop-up to select RScript. 

Also I noticed in Terminal within RStudio, it does not take any input (none at all). 

I am happy to use existing VMs, just need crontab facility somehow. Please suggest if there are any other alternatives.

**Comment by jwijffels** [comment]
Closing as no active feedback given in last month.
