### ISSUE TITLE
Allow user to specify working directory for RScript?

### ISSUE THREAD

**Issue by cboettig** [bnosac/cronR#30]
the behaviour of RScript can depend on a working directory (e.g. for a .Renviron that may contain credentials needed, etc).  Of course we can construct our commands from scratch and add them with cron_add(), but it would be great if `cron_rscript()` could support an argument of `workdir` that would add a `cd workdir` before evaluating Rscript.  If this sounds reasonable to you I'd be happy to prepare a PR.

**Comment by jwijffels** [comment]
Good point. Allows to pass on different environment variables and settings. Feel free to create a PR

**Comment by jwijffels** [comment]
Thanks. On cran now.
