### ISSUE TITLE
Setting the cron for different timezone

### ISSUE THREAD

**Issue by adeel1997** [bnosac/cronR#35]
Thanks for this great package. Is there a possibility of setting up cron at a different timezone??

**Comment by jwijffels** [comment]
Me querying google: 
https://serverfault.com/questions/791713/what-time-zone-is-a-cron-job-using#:~:text=Cron%20job%20uses%20the%20server%27s,the%20date%20command%20in%20terminal.

**Comment by adeel1997** [comment]
Thanks @jwijffels I have precisely tried that actually. I changed my server time. But it's not really working.  I have restarted my server too for the changes to be made.

**Comment by adeel1997** [comment]
I got a fixed. First by changing my server timezone. Then I think it's important to restart the corn to really work. I used this command:
sudo service cron restart

It's working now.
