### ISSUE TITLE
Schedule job every 15 min

### ISSUE THREAD

**Issue by j-Rinehart** [bnosac/cronR#5]
I can see how you would use `days_of_month` or `days_of_week` to modify the `frequency=daily` for example, but is it possible in the script or (ideally) in the add-in to modify `minutely` to run every 15 minutes?

**Comment by jwijffels** [comment]
I've updated the package and showed how to do this. See readme or cron_add. Can you test.

**Comment by j-Rinehart** [comment]
Totally worked!  I testing both with `cron_add()` syntax as well as in the add-in tool.  Both worked perfectly.

**Comment by jwijffels** [comment]
FYI. The same question was basically asked in https://github.com/bnosac/cronR/issues/1
It was already possible to schedule a cron script every x minutes

`cron_add(cmd, frequency = 'hourly', at = c(3,18, 33, 48), id = 'jobid', description = 'jobdescription')`

But now it's also possible to specify this in whichever cron format you like 

`cron_add(cmd, frequency = '*/15 * * * *', id = 'job10', description = 'Every 15 min')   `

So the above 2 basically do the same

**Comment by j-Rinehart** [comment]
Great…just pulled the new update through…thanks for the head’s up.

BTW..if I am kicking off the cron job through the add-in…is it possible to add:  
log_append = FALSE somewhere?

Assuming that overwrites the log each time…correct?

**Comment by jwijffels** [comment]
In the RStudio add-in logs are always appended, the log_append argument is not put in the GUI. From the command line you can use cron_rscript which has the argument log_append

**Comment by jwijffels** [comment]
This package also saves me quite some time. Good that this has solved your problem. If you have different needs regarding logging, please create a new issue.
