### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by DamonDay** [bnosac/cronR#53]
please help check, it seems like the administrator access for Rstudio is not permitted, but what else can I do?
macOS Monterey Version 12.3.1
13-inch, M1, 2020
RStudio
2022.02.0 Build 443
the log said: Fatal error: cannot open file '/Users/../myR.R': Operation not permitted
![image](https://user-images.githubusercontent.com/24534739/190333667-7aaa3170-9a82-45a2-970b-40b5d65b3b76.png)
![image](https://user-images.githubusercontent.com/24534739/190333766-59fa5577-f08f-487f-9f94-dc768573ce6a.png)
![image](https://user-images.githubusercontent.com/24534739/190333842-daabbb56-cb23-4f1f-948f-9ba43d1810f7.png)

**Comment by jwijffels** [comment]
Looks like the same issue as https://github.com/bnosac/cronR/issues/17

**Comment by DamonDay** [comment]
> Looks like the same issue as #17

Yes, it helps! thanks a lot!
