### ISSUE TITLE
Unable to install cronR

### ISSUE THREAD

**Issue by lollex90** [bnosac/cronR#54]
Hello, 

as per the title I am unable to install the package when I call ```install.packages("cronR")```. I am getting a warning saying that this package does not exist for my version of R (I am using 4.2.1). I tried installing via github but that didn't work either. Thanks for your help in advance!

**Comment by jwijffels** [comment]
cronR is for unix-only (e.g. Linux/Mac), if you are on Windows, you can use R package taskscheduleR
