### ISSUE TITLE
Is there a way to "catch-up" a Cron job if the system was asleep?

### ISSUE THREAD

**Issue by samuelreuther** [bnosac/cronR#55]
Just a question if it was possible to use anacron instead of cron?
(Same requirement here: https://stackoverflow.com/questions/70828497/r-understanding-how-scheduled-tasks-are-stored-when-the-computer-is-turned-off)
Thank you!

**Comment by jwijffels** [comment]
This package is an R wrapper around cron, not anacron. 
Free free to use the code in the package to make another package which works for anacron. There are no plans to provide this from my end.

**Comment by samuelreuther** [comment]
Thank you very much for the quick response! And of course I understand your position. Unfortunately I am not sure if I have the skills to get an anacronR package to work. Maybe I'll give it a try, though. All the best!
