### ISSUE TITLE
Unable to install this package from either Github or CRAN

### ISSUE THREAD

**Issue by Neo005** [bnosac/cronR#56]
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
Warning in install.packages :
  unable to access index for repository https://github.com/bnosac/cronR/bin/windows/contrib/4.0:
  cannot open URL 'https://github.com/bnosac/cronR/bin/windows/contrib/4.0/PACKAGES'

**Comment by jwijffels** [comment]
See the 1st paragraph in the README

> This allows R users working on **Unix/Linux** to automate R processes at specific timepoints from R itself. Note that if you are looking for a Windows scheduler, you might be interested in the R package taskscheduleR available at https://github.com/bnosac/taskscheduleR

You are on Windows.
