### ISSUE TITLE
Using www-data as a user

### ISSUE THREAD

**Issue by OdilKurbanov** [bnosac/cronR#58]
Hi there,
Thanks for a great package. I'm currently testing cronR. I'm trying to add a new cron on behalf of 'www-data' user from myuser account in RStudio 
```R
library(cronR)
f <- glue('/home/myuser/testfolder/crontesting.R')
cmd <- cron_rscript(f)
# cmd

cron_add(command = cmd, frequency = 'minutely', id = 'test1', user = 'www-data')

# cron_njobs()
# cron_ls()
```
But cron is added on behalf of myuser:

```R
cron_ls(user='myuser')
## cronR job
## id:   test1
## tags: 
## desc: 
# 0-59 * * * * /usr/lib/R/bin/Rscript '/home/myuser/myfolder/crontesting.R'  >> '/home/myuser/myfolder/crontesting.log' 2>&1
```
And not for www-data user
```R
cron_ls(user='www-data')
# No cron jobs available for user 'www-data'.
```
What could be the problem?
Thank you!

**Comment by OdilKurbanov** [comment]
> Does user myuser has appropriate rights to see and modify cronjobs of user www-data?

Thank you for your prompt reply. Yes, `myuser` is a member of the www-data group.

**Comment by OdilKurbanov** [comment]
Thank you for further looking into this. I tested from my www-data user too. I'm able to add a cron job but `user=myuser` is not changing the owner, cron is added for www-data user.

**Comment by jwijffels** [comment]
Yes, the package is changing the cron job currently only for the current logged in user

**Comment by jwijffels** [comment]
I've made the changes in commit to honour the use of argument `user` in `cron_add` and `cron_rm`.
Can you install the development version with `remotes::install_github("bnosac/cronR")` and let me know how it goes.

**Comment by OdilKurbanov** [comment]
I installed the dev version and run cron_add command
```R
cron_add(command = cmd, frequency = 'minutely', id = 'test1', user = 'www-data')
```
and I was asked before adding this cron
```R
Are you sure you want to add the specified cron job: '/usr/lib/R/bin/Rscript '/home/myuser/testfolder/crontesting.R' >> '/home/myuser/testfolder/crontesting.log' 2>&1'? [y/n]
```
then I checked number of cron jobs by users:
```R
cron_njobs(user='www-data')
# No cron jobs available for user 'www-data'.

cron_njobs(user='myuser')
#There are a total of 1 cronR cron jobs and 0 other cron jobs currently running.
```
Seems cronR version 0.6.4 is not respecting user='www-data' yet.

Thank you for your effort.

**Comment by jwijffels** [comment]
Can't reproduce this behaviour. I get the following. Note the `must be privileged to use -u`. If I run this as root. The cronjob is put for user www-data

```
> myscript <- system.file("extdata", "helloworld.R", package = "cronR")
> 
> f   <- system.file(package = "cronR", "extdata", "helloworld.R")
> cmd <- cron_rscript(f)
> cron_add(command = cmd, frequency = 'minutely', id = 'abc', description = 'My process 1', user = "www-data")
Are you sure you want to add the specified cron job: '/usr/lib/R/bin/Rscript '/home/jwijffels/R/x86_64-pc-linux-gnu-library/3.6/cronR/extdata/helloworld.R'  >> '/home/jwijffels/R/x86_64-pc-linux-gnu-library/3.6/cronR/extdata/helloworld.log' 2>&1'? [y/n]: 
1: y
Adding cronjob:
---------------

## cronR job
## id:   abc
## tags: 
## desc: My process 1
0-59 * * * * /usr/lib/R/bin/Rscript '/home/jwijffels/R/x86_64-pc-linux-gnu-library/3.6/cronR/extdata/helloworld.R'  >> '/home/jwijffels/R/x86_64-pc-linux-gnu-library/3.6/cronR/extdata/helloworld.log' 2>&1
must be privileged to use -u
```

**Comment by OdilKurbanov** [comment]
Let me double-check, I will get back to you with the result. Thanks

**Comment by OdilKurbanov** [comment]
I'm checking with user in sudo group but not root, and getting `must be privileged to use -u` warning.
Looking how to grant using `-u` . Will update on progress.
