### ISSUE TITLE
Support for R Version 4.2.2

### ISSUE THREAD

**Issue by Neo005** [bnosac/cronR#60]
Kindly please make this package work with the latest R version (e.g. R version 4.2.2)

R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> install.packages("cronR")
Warning in install.packages :
  package ‘cronR’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by jwijffels** [comment]
The first line in the readme mentions

Schedule R scripts/processes with the cron scheduler. This allows R users working on **Unix/Linux** to automate R processes at specific timepoints from R itself. _Note that if you are looking for a Windows scheduler, you might be interested in the R package taskscheduleR available at https://github.com/bnosac/taskscheduleR_
