### ISSUE TITLE
Use normalizePath for rscripts and other paths.

### ISSUE THREAD

**Issue by llrs** [bnosac/cronR#63]
I had problems running a cron job because the path was not executed in the right directory. I would prefer `cron_rscript()` to have by default to set the workdir to `dirname(rscript)` by default.

However, another problem presented when I used relative paths to define where the rscript was. I would suggest to use `normalizePath` to make sure that all the paths are absolute and so they can be run. If desired, I can send a PR too.

**Comment by jwijffels** [comment]
There is already argument `workdir ` in cron_rscript which was put into the function with this pull request: https://github.com/bnosac/cronR/pull/31. 
Maybe that is something you are looking for?
About the relative paths. There is already something implemented regarding the current working directory here: https://github.com/bnosac/cronR/blob/master/R/cron_rscript.R#L52-L56

**Comment by llrs** [comment]
The "problem" was that by default the `workdir` is not used. 

It only appends the working directory if the file is the same as the rscript. 
If the current working directory is not where the r script is it doesn't work well. That's why I am suggesting to use `normalizePath` to set the full path to the rscript regardless of the working directory..

**Comment by jwijffels** [comment]
> The "problem" was that by default the workdir is not used.

Yes, the default of workdir is NULL. 

> It only appends the working directory if the file is the same as the rscript.

Which part of which function are you referring to?
