### ISSUE TITLE
cronR not working

### ISSUE THREAD

**Issue by zachasman** [bnosac/cronR#7]
@jwijffels Sorry about that. So yeah, my script won't run. Is there any way I can check if an attempt was made? What am I doing wrong? For reference, here are some screenshots of the inputs on the add-in.

<img width="691" alt="1" src="https://user-images.githubusercontent.com/26579947/38323921-b0852d46-380c-11e8-8a49-9df3965ed56d.png">

<img width="694" alt="2" src="https://user-images.githubusercontent.com/26579947/38323924-b351f018-380c-11e8-9199-6e2cd992a1f0.png">

Assuming I didn't do the crontab code incorrectly, that should have run at 1:30PM EST. But did not.

**Comment by jwijffels** [comment]
Did you solve your problem yourself? Feel free to share what you did.
