### ISSUE TITLE
Path Name with Spaces

### ISSUE THREAD

**Issue by EvanFalcone** [bnosac/cronR#8]
I seem to be experiencing similar issues with the cronR add-in for Unix/Linux as have been reported for the taskscheduleR Windows equivalent: I am not able to add jobs for scripts with a space in the path name.

As other users have pointed out (for taskscheduleR), I don't have access to changing the file path names in production due to IT. Would it be possible to fix this for cronR as was done for taskscheduleR?

Thank you in advance and thank you for a great add-in/package!

**Comment by jwijffels** [comment]
Can you provide a reproducible example

**Comment by jwijffels** [comment]
Can you indicate what this give on your computer ```
file.path(Sys.getenv("R_HOME"), "bin",
  "Rscript")
```

**Comment by EvanFalcone** [comment]
I have to apologize, jwijffels, as it appears to be working today. I've copy-pasted the warning I was getting below in case someone else runs into it - although it's just a warning, the cron job was still not executing yesterday. However, I ran it again today and the cron job now appears in the crontab schedule.

`Warning in getSelectedFile(inputui = input$fileSelect) :
  It is advised that the file you want to schedule (/home/fevan/Evan_-_Pricing/4 Replicate Sales Dashboards/Cron Job Test.R) does not contain spaces`

As for the file.path() test, I get the following output:

`"/usr/lib/R/bin/Rscript"`

Apologies for any inconvenience! Going ahead and closing this issue.

**Comment by jwijffels** [comment]
Paths to R scripts can contains spaces but it is not advised, that is what the warning message tells you. 
The path to R itself can not contain spaces. But for your case `"/usr/lib/R/bin/Rscript"` does not contain a space.

**Comment by EvanFalcone** [comment]
Yes - the cron job was still not being added to the crontab schedule and the warning was all I had to go off of. It seems to add fine today; might have been a change in environment as I'm not the only user on the server. In any case, I appreciate your time and help!
